#! /bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://github.com/sddo-gcj/app-4721960K-repo
ls -l
cp -p /tmp/clone/app-4721960K/new_4721960K_index.html /var/www/html
